site_name: Explain to 5 year old
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue grey
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: black)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: ./assets/logo.png
  favicon: ./assets/logo.png
  
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
    - search
repo_url: https://github.com/krishnaglodha/explainto5yearold
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/krishnaglodha
    - icon : fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/krishnaglodha/
    - icon : fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCwWQRgxtYxUZHSPB5JKjNIA
copyright: Copyright &copy; 2023 Krishna G. Lodha

nav:
    - Home: index.md
    
    - Frontend : 
      - Frontend/index.md
      - Frontend/html.md
      - Frontend/css.md
      - Frontend/JavaScript.md
    - Database : 
      - Database/index.md
    - Backend : 
      - Backend/index.md